# Generated by Django 4.0.4 on 2022-05-04 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='user',
        ),
    ]
