# Generated by Django 4.0.4 on 2022-04-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='announcement',
        ),
        migrations.AddField(
            model_name='announcements',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='message',
            field=models.TextField(),
        ),
    ]
