# Generated by Django 4.0.4 on 2022-04-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0002_remove_announcements_announcement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
